name: Development (Working Draft) PR Checks Workflow
on:
  pull_request: 
    branches: [] # [dev]

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      # Setup:
      - uses: actions/checkout@v4

      # ---

      - name: Validate Commit Messages
        run: _

      # ---

      # Skip if no changes / Atomic Testing
      - name: Testing
        run: _

      # Skip if no changes
      - name: Code Coverage
        run: _

      # Skip if no changes
      - name: Code Speed
        run: _
        
      # ---
      
      - name: Generate Documentation
        run: |
          deno doc --html
      
      # TODO: Only check the documentation that is "newly generated" / "changed"
      - name: Documentaation Checks
        run: |
          deno doc --html
          echo "JSR Package Checks"
          echo "JS/TS Docs Checks"
          echo "Astro Docs Checks"

      # ---

      - name: Publish Summary
        run: _

      #  ---

      - name: Output candidate version number
        uses: actions/github-script@v7
        with:
          script: |
            const package = require(`${process.env.GITHUB_WORKSPACE}/package.json`)
            github.rest.repos.createCommitStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              sha: context.sha,
              state: 'success',
              context: `Published ${package.name}`,
              description: package.version,
              target_url: `https://unpkg.com/${package.name}@${package.version}/`
            })
