name: Publish
on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: JS/TS Docs Checks
        run: deno doc --html

      - name: Astro Docs Checks
        run: deno doc --html

      - name: JSR Package Checks
        run: deno doc --html

      - name: Code Coverage and Tests
        run: deno doc --html

      - name: Validate Commit Messages
        run: deno doc --html

      - name: Validate Versioning
        # TODO: PRINT VERSION BUMPS `FROM` -> `TO`
        run: deno doc --html

      - name: Validate Changelog
        # TODO: PRINT CHANGELOG AS IT SHALL APPEAR IN RELEASE
        run: deno doc --html

      - name: Publish Summary
        run: deno doc --html

        #  ----
      - name: Output candidate version number
        uses: actions/github-script@v7
        with:
          script: |
            const package = require(`${process.env.GITHUB_WORKSPACE}/package.json`)
            github.rest.repos.createCommitStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              sha: context.sha,
              state: 'success',
              context: `Published ${package.name}`,
              description: package.version,
              target_url: `https://unpkg.com/${package.name}@${package.version}/`
            })

          # TODO: When a major has to be merged, change the base of the git to  make sure we can track the major changes from the very start