name: Publish
on:
  push:
    branches:
      - main

jobs:
  pre-release:
    import: pre-release.yml

  release:
    last-step: if success
  
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Increment Versions
        run: Increment Versions inside of Packages

      - name: Update Changelog in Docs
        run: Increment Versions inside of Packages

      - name: Publish Packages Release on GitHub
        run: Increment Versions inside of Packages

      - name: Deployment of Docs on GitHub
        run: Increment Versions inside of Packages

  publish:
    # TODO: Run pre-release and if success, only the continue:
    last-step: if success
  
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Publish package on NPM
        run: bunx npm publish
        
      - name: Publish package on JSR
        run: bunx jsr publish

      - name: Generate Provenance
        run: generate provenance
